# Generated by Django 2.2.2 on 2019-07-17 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HOME', 'HOME'), ('PERSONAL', 'PERSONAL'), ('ANAND_RESORT', 'ANAND_RESORT'), ('ANAND_MOTEL', 'ANAND_MOTEL'), ('ANAND_KITCHEN', 'ANAND_KITCHEN')], default=None, max_length=100)),
                ('Trxn_Amt', models.FloatField()),
                ('Created_On', models.DateTimeField()),
                ('Paid_to', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, max_length=1000)),
                ('created_Entry_date', models.DateField(default=datetime.date.today, editable=False)),
            ],
            options={
                'verbose_name': 'My_Expense',
                'verbose_name_plural': 'My_Expenses',
                'db_table': ' My_Expense',
            },
        ),
        migrations.CreateModel(
            name='To_do_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HOME', 'HOME'), ('PERSONAL', 'PERSONAL'), ('ANAND_RESORT', 'ANAND_RESORT'), ('ANAND_MOTEL', 'ANAND_MOTEL'), ('ANAND_KITCHEN', 'ANAND_KITCHEN')], default=None, max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Done_or_Not_Done', models.BooleanField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(default='2019-07-17')),
            ],
            options={
                'verbose_name': 'To_do_List',
                'verbose_name_plural': 'To_do_Lists',
                'db_table': ' To_do_List',
            },
        ),
        migrations.CreateModel(
            name='ToDoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ToDoCategory',
                'verbose_name_plural': 'ToDoCategories',
                'db_table': 'ToDoCategory',
            },
        ),
    ]
