# Generated by Django 2.2.2 on 2020-01-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='due_date',
            field=models.DateField(default='2020-01-03'),
        ),
    ]
