
       

HOME ='HOME'
PERSONAL ='PERSONAL'
ANAND_RESORT = 'ANAND_RESORT'
ANAND_MOTEL = 'ANAND_MOTEL'
ANAND_KITCHEN ='ANAND_KITCHEN'

Category_choices = [
    (HOME, 'HOME'),
    (PERSONAL, 'PERSONAL'),
    (ANAND_RESORT, 'ANAND_RESORT'),
    (ANAND_MOTEL, 'ANAND_MOTEL'),
    (ANAND_KITCHEN, 'ANAND_KITCHEN'),
    ]




